site_name: Stalker Anomaly Modding
site_author: Razor Shultz
copyright: "Documentation by Razor Shultz"

theme:
    name: material
    palette:
        scheme: slate
        primary: red
    features:
    - navigation.footer
    - navigation.top

nav:
    - Home: index.md
    - MCM: 
        - Intro to MCM: MCM-intro.md
        - Creating MCM menu items: MCM-2.md

extra_css:
    - extra.css

extra:
    generator: true
    social:
        - icon: fontawesome/brands/discord
          link: https://discord.gg/anomalymod
          name: AnomalyMod on Discord



